### ISSUE TITLE
[Warning] Unknown class passed as parameter

### ISSUE THREAD

**Issue by torleif** [silverstripe-labs/silverstripe-fulltextsearch#101]
Using PHP < [5.3.7 is_subclass_of() causes an error](http://php.net/manual/en/function.is-subclass-of.php#refsect1-function.is-subclass-of-changelog) when indexing a class with an Enum object. The enum passes parameters into the function causing the warning. 

A fix would be to modify **addAllFulltextFields(...)** in SearchIndex.php to strip the parentheses and check if the function exists first: 

```php
	public function addAllFulltextFields($includeSubclasses = true) {
		foreach ($this->getClasses() as $class => $options) {
			foreach (SearchIntrospection::hierarchy($class, $includeSubclasses, true) as $dataclass) {
				$fields = DataObject::database_fields($dataclass);

				foreach ($fields as $field => $type) {
					if (preg_match('/^(\w+)\(/', $type, $match)) $type = $match[1];
					$type = preg_replace('/\s*\([^)]*\)/', '', $type);
					if (class_exists($type) && is_subclass_of($type, 'StringField')) $this->addFulltextField($field);
				}
			}
		}
	}

```

**Comment by tractorcow** [comment]
Is Enum being treated as a fulltext field even correct behaviour? 

There's also this you could use as a clean alternative.

```php
list($type, $args) = Object::parse_class_spec($type);
```

**Comment by torleif** [comment]
Thanks @tractorcow. I'd assume some people would want the content of Enums searched, I'm not fazed. 

Your fix is much better, I spent some time looking at this issue and it's similar to what Typo3 did when they had the same problem

**Comment by torleif** [comment]
Fixed with https://github.com/silverstripe-labs/silverstripe-fulltextsearch/pull/104
