### ISSUE TITLE
Delete 2.4 branch - it's super confusing

### ISSUE THREAD

**Issue by dhensby** [silverstripe-labs/silverstripe-fulltextsearch#124]
Yo - the 2.4 branch is the first ever version of fulltextsearch (I assume for SS2.4) and as we are on release 2.2 at the moment, it's quite confusing to have this branch and will probably cause problems in times soon to come

**Comment by tractorcow** [comment]
I've renamed to `2.4-compat`, so at least it's not a numeric version anymore.
