### ISSUE TITLE
`SearchVariant` replaced by `Injector` not consistent when used as part of `_documentid`

### ISSUE THREAD

**Issue by michalkleiner** [silverstripe-labs/silverstripe-fulltextsearch#348]
Still trying to figure out what is going on, but the gist is that we are replacing a sublass of SearchVariant with a custom subclass of it via Injector to add an extension point to it.

When checking Solr log, documents added to or updated in the solr index have `_documentid` field containing both the original and the replace variant as part of the id whereas the delete action does not have the original variant in the id, effectively causing the documents not being removed from Solr index on an unpublish action. The front-end still does `canView` check before displaying the results, so this doesn't cause a problem in terms of visibility of stale search results, but in places where a set number of results is expected it may mean Solr e.g. returns 3 but FE only displays 2 items.

## PRs
- https://github.com/silverstripe/silverstripe-fulltextsearch/pull/349

**Comment by GuySartorelli** [comment]
Merged and tagged
