### ISSUE TITLE
Deprecated code PHP 8.2

### ISSUE THREAD

**Issue by alex-dna** [silverstripe-labs/silverstripe-fulltextsearch#353]
Hi,

I'm getting some deprecation warning when running Solr_Configure and Reindex in PHP 8.2.

ERROR [Deprecated]: Creation of dynamic property SilverStripe\FullTextSearch\Solr\Stores\SolrConfigStore_File::$remote is deprecated

I think it is an easy fix, I'll prepare a PR.

**Comment by alex-dna** [comment]
https://github.com/silverstripe/silverstripe-fulltextsearch/pull/354

**Comment by GuySartorelli** [comment]
PR merged. This will be automatically tagged by GitHub actions
