### ISSUE TITLE
Wrong inclusion of Phockito in SolrReindexTest and SolrIndexVersionedTest

### ISSUE THREAD

**Issue by extravio** [silverstripe-labs/silverstripe-fulltextsearch#89]
The inclusion of Phockito::include_hamcrest() should be limited to the test execution as per:
https://github.com/hafriedlander/silverstripe-phockito/

This is not the case in SolrReindexTest and SolrIndexVersionedTest which makes running the tests impossible because of the PHP Fatal error:  Cannot redeclare any() (previously declared in [...]/vendor/hafriedlander/phockito/hamcrest-php/hamcrest/Hamcrest.php:384) in [...]/vendor/phpunit/phpunit/PHPUnit/Framework/Assert/Functions.php on line 59

**Comment by madmatt** [comment]
Hi @extravio, I believe that I fixed this with pull request #102 - can you confirm if they work for you once you apply that patch?

**Comment by tractorcow** [comment]
Looks like it has been. ;D
