### ISSUE TITLE
user feedback for Solr_Configure

### ISSUE THREAD

**Issue by jakedaleweb** [silverstripe-labs/silverstripe-fulltextsearch#95]
In CWP 1.1.1 and up there is no feedback for a successful Solr_Configure run through the browser, it would be nice to get a message similar to earlier versions so the user can be sure the Configure was successful.

![screen shot 2015-11-19 at 4 57 14 pm](https://cloud.githubusercontent.com/assets/11186642/11262018/f3117798-8ede-11e5-94b1-7bd5daf1e2e6.png)

**Comment by phptek** [comment]
+1

**Comment by tractorcow** [comment]
Please put ?verbose=1 into the querystring if you want output :D
